import Head from "next/head";
import { Box, Heading, Text, Link } from "@chakra-ui/react";
import NavBar from "../components/NavBar";
import FooterComponent from "../components/Footer";
import CashBack from "../components/CashBackMethod";
import NextLink from "next/link";
import Image from "next/image";
import picture1 from "../public/homepage-firstpic.svg";
import picture2 from "../public/homepage-secondpic.svg";
import icon1 from "../public/homepage/1.svg";
import icon2 from "../public/homepage/2.svg";
import icon3 from "../public/homepage/3.svg";
import icon4 from "../public/homepage/4.svg";
import icon5 from "../public/homepage/5.svg";
import icon6 from "../public/homepage/6.svg";
import playbutton from "../public/homepage/playbutton.svg";
import reason1 from "../public/homepage/reasons1.svg";
import reason2 from "../public/homepage/reason2.svg";
import reason3 from "../public/homepage/reason3.svg";
import reason4 from "../public/homepage/reason4.svg";
import rightellipse from "../public/navassets/rightellipse.png";
import leftellipse from "../public/navassets/leftellipse.png";

export default function Home() {
  const options = [
    ["Play with profile", "/register"],
    ["Play from ATM", "/cashback-atm"],
    ["Cashout", "/cashout"],
  ];
  return (
    <div>
      <Head>
        <title>NairaBoom</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <NavBar />
      <Box
        bgColor={"#F7F7F7"}
        display="flex"
        flexDir={{base:"column", lg:"row"}}
        justifyContent={"center"}
        height="max-content"
        alignItems="center"
        pt={{ base: "4rem", md: "5rem" }}
        pb={{ base: "0rem", lg: "0" }}
        gap={{base:"2rem", lg:"0"}}
      >
        <Box
          display={"flex"}
          flexDir="column"
          w={{ base: "90%", md: "50%", lg: "33%" }}
          fontFamily={"poppins"}
        >
          <Heading
            color={"nairablue"}
            fontWeight={"800"}
            fontSize={{ base: "2.5rem", lg: "3rem" }}
            lineHeight={{ base: "3.5rem", lg: "4rem" }}
            fontFamily="poppins"
          >
            Get up to 500% cashback on withdrawals
          </Heading>
          <Text pt={".8rem"} w="100%">
            Get up to 500% percent cash back payout whenever you withdraw from
            any ATM in Nigeria.
          </Text>
          <NextLink href="/guest" passHref>
            <Link
              fontWeight={600}
              bgColor="nairagreen"
              color="white"
              borderRadius="md"
              transitionDuration={".3s"}
              _hover={{ transform: "scale(1.02)" }}
              textAlign="center"
              py={"1rem"}
              w="100%"
              mt="1.5rem"
              boxShadow={"inner"}
              bgGradient="linear(180deg, #02D95A 0%, #02B54C 100%)"
            >
              Play as guest
            </Link>
          </NextLink>
          <Box
            w="100%"
            display={"flex"}
            justifyContent="space-between"
            pt="1.5rem"
          >
            {options.map((option, index) => (
              <NextLink key={index} href={option[1]} passHref>
                <Link
                  fontWeight={500}
                  bgColor="white"
                  color="black"
                  borderRadius="md"
                  w={{ base: "max-content", md: "30%" }}
                  px={{ base: ".6rem" }}
                  boxShadow="md"
                  h={{ base: "fit-content", sm: "2rem" }}
                  textAlign={"center"}
                  fontSize="12px"
                  pt=".5rem"
                  transitionDuration={".3s"}
                  _hover={{ boxShadow: "xl" }}
                >
                  {option[0]}
                </Link>
              </NextLink>
            ))}
          </Box>
        </Box>
        <Box
          w={{ md: "40%", lg: "50%" }}
          // display={{ base: "none", lg: "block" }}
        >
          <Image src={picture1} alt="picture 1" />
        </Box>
      </Box>

      <Box
        bgColor={"white"}
        fontFamily="poppins"
        display={"flex"}
        flexDir={{ base: "column", lg: "row" }}
        gap={{ base: "2rem", lg: "0" }}
        alignItems="center"
        justifyContent={"space-evenly"}
        py={{ base: "3rem", lg: "5rem" }}
      >
        <Box display={{ base: "none", lg: "block" }}>
          <Image src={picture2} alt="homepage second picture" />
        </Box>
        <Box
          display={"flex"}
          gap="1.5rem"
          flexDir="column"
          w={{ base: "90%", lg: "50%" }}
          float={"right"}
        >
          <Text fontWeight={500} color="nairagreen">
            About Us
          </Text>
          <Heading
            fontFamily={"poppins"}
            fontSize={{ base: "2rem", lg: "2.5rem" }}
          >
            Africa’s pioneer Electronic Transaction Request Back Service
          </Heading>
          <Text color={"#767676"} fontSize="xl">
            NairaBoom is Africa’s premier/pioneer Electronic Transaction Request
            Back Service (ETRS) that scores and rewards users with cashback,
            refunds ,giveaway and payouts for electronic financial transactions
            they register with the service.
          </Text>
          <Text color={"#767676"} fontSize="xl" pt="1rem">
            9jaCashBack is available to every ATM debit card holder and bank
            account owner in Nigeria and can be accessed directly from web,
            mobile, USSD or any ATM across Nigeria.
          </Text>
          <NextLink href={"/about"} passHref>
            <Link
              w="11rem"
              p="1rem"
              borderRadius={"lg"}
              textAlign={"center"}
              bgColor={"nairagreen"}
              color="white"
              fontWeight={600}
              transitionDuration={".3s"}
              _hover={{ transform: "scale(1.02)" }}
              mt="1rem"
            >
              Read More
            </Link>
          </NextLink>
        </Box>
      </Box>
      <Box
        fontFamily={"poppins"}
        py={{ base: "2rem", md: "8rem", lg: "11rem" }}
        display={"flex"}
        flexDir="column"
        alignItems={"center"}
        px={{ base: "2rem", lg: "6rem" }}
        bgColor={"white"}
      >
        <Heading fontFamily={"poppins"} pb={{ base: "3rem", md: "5rem" }}>
          Easy Steps To Win Cashback Daily
        </Heading>
        <Box
          display="flex"
          flexWrap={"wrap"}
          gap="3rem"
          justifyContent={"center"}
        >
          <CashBack
            number={1}
            icon={icon1}
            title="Recieve a Credit or Debit Alert"
            note="Whenever you receive a credit or debit alert, log on to www.9jacashback.com to
            request your cashback. "
          />
          <CashBack
            number={2}
            icon={icon2}
            title="Register Your Alert"
            note='Click "Play Cashback as a Guest" to request with just your phone number or "Play Cashback With Profile"  to register and request from your Profile.'
          />
          <CashBack
            number={3}
            icon={icon3}
            title="Fill a Wish Form"
            note="Fill out the wish form with details of the transaction you are requesting cashback for, Choose your Lucky time (any random time)."
          />
          <CashBack
            number={4}
            icon={icon4}
            title="Confirm and Submit Your Ticket"
            note="Confirm and Submit your ticket for your cashback request."
          />
          <CashBack
            number={5}
            icon={icon5}
            title="Pay Your Clock Token"
            note="Pay your clock token and save your entry ticket."
          />
          <CashBack
            number={6}
            icon={icon6}
            title="Check The Latest Lucky
            Cashback Time"
            note='Check the daily "Latest Lucky Cashback Time" at 12 midnight on the website or any of our social media pages to see if you won.'
          />
        </Box>
        <NextLink href={"/how-it-works"} passHref>
          <Link
            bgColor={"nairagreen"}
            color="white"
            fontWeight={600}
            fontSize="lg"
            p="1rem 3rem"
            mt="4.5rem"
            borderRadius={"md"}
            transitionDuration={".3s"}
            _hover={{ transform: "scale(1.02)" }}
          >
            Load More
          </Link>
        </NextLink>
      </Box>
      <Box
        bgColor={"nairablue"}
        display="flex"
        flexDir={{ base: "column", md: "row" }}
        fontFamily={"poppins"}
        py={{ base: "4rem", md: "6.5rem" }}
        justifyContent={"center"}
        gap={{ base: "1rem", md: "5rem" }}
        alignItems={"center"}
        backgroundImage={{
          base: `url(${rightellipse.src}), url(${leftellipse.src})`,
          md: `url(${rightellipse.src}), url(${leftellipse.src})`,
        }}
        backgroundPosition={{
          base: "right top, left bottom",
          md: "right center, left center",
        }}
        backgroundRepeat="no-repeat"
        mt="1rem"
      >
        <Box display={"flex"} alignItems="center">
          <Box as={Link}>
            <Image src={playbutton} alt="video play button" />
          </Box>
          <Text color={"white"} fontSize="lg">
            Watch to learn more
          </Text>
        </Box>
        <NextLink href={"/"} passHref>
          <Link
            bgColor={"nairagreen"}
            color="white"
            fontWeight={600}
            fontSize="lg"
            p=".8rem 4rem"
            borderRadius={"md"}
            transitionDuration={".3s"}
            _hover={{ transform: "scale(1.02)" }}
          >
            Play Now
          </Link>
        </NextLink>
      </Box>
      <Box
        display={"flex"}
        fontFamily={"poppins"}
        bgColor="#F5F5F5"
        pt={"5rem"}
        flexDir="column"
        alignItems={"center"}
        pb="10rem"
      >
        <Heading
          fontWeight={700}
          fontSize={{ base: "1.6rem", lg: "2.5rem" }}
          fontFamily={"poppins"}
          color="nairablue"
          pb={{ base: "5rem", md: "8rem" }}
          textAlign="center"
        >
          Why Request Cashback?
        </Heading>
        <Box display={"flex"} flexDir="column" gap={{base:"5rem" ,md:"8rem"}}>
          <Box
            display={"flex"}
            flexDir={{ base: "column", md: "row" }}
            justifyContent="space-evenly"
            alignItems={"center"}
            gap="1rem"
          >
            <Box w={{ base: "70%", md: "max-content" }}>
              <Image src={reason1} alt="cashback reason" />
            </Box>

            <Box
              display="flex"
              flexDir="column"
              gap="2.2rem"
              w={{ base: "90%", md: "50%" }}
            >
              <Text color="nairablue" fontWeight={700} fontSize="25px">
                Up to 500% Cashback on ATM withdrawals
              </Text>
              <Text color="nairablue" fontSize={"25px"}>
                Get up to 500% percent cash back payout whenever you withdraw
                from any ATM in Nigeria.
              </Text>
            </Box>
          </Box>

          <Box
            display={"flex"}
            justifyContent="space-evenly"
            flexDir={{ base: "column", md: "row-reverse" }}
            alignItems="center"
            gap="1rem"
          >
            <Box w={{ base: "70%", md: "max-content" }}>
              <Image src={reason2} alt="cashback reason" />
            </Box>
            <Box
              display="flex"
              flexDir="column"
              gap="2.2rem"
              w={{ base: "90%", md: "50%" }}
              textAlign={{ base: "left", md: "right" }}
            >
              <Text color="nairablue" fontWeight={700} fontSize="25px">
                Up to 100% Cashback on transfers and POS payments
              </Text>
              <Text color="nairablue" fontSize={"25px"}>
                Get back up to 100% Cashback of whatever local bank to bank
                transfer you make daily or any POS payment you make across
                Nigeria.
              </Text>
            </Box>
          </Box>
          <Box
            display={"flex"}
            justifyContent="space-evenly"
            flexDir={{ base: "column", md: "row" }}
            alignItems="center"
            gap="1rem"
          >
            <Box w={{ base: "70%", md: "max-content" }}>
              <Image src={reason3} alt="cashback reason" />
            </Box>
            <Box
              display="flex"
              flexDir="column"
              gap="2.2rem"
              w={{ base: "90%", md: "50%" }}
            >
              <Text color="nairablue" fontWeight={700} fontSize="25px">
                Random Daily Giveaway
              </Text>
              <Text color="nairablue" fontSize={"25px"}>
                Get Random give away cash out just because you used the ATM, POS
                or made a transfer.
              </Text>
            </Box>
          </Box>

          <Box
            display={"flex"}
            justifyContent="space-evenly"
            flexDir={{ base: "column", md: "row-reverse" }}
            alignItems="center"
            gap="1rem"
          >
            <Box w={{ base: "70%", md: "max-content" }}>
              <Image src={reason4} alt="cashback reason" />
            </Box>
            <Box
              display="flex"
              flexDir="column"
              gap="2.2rem"
              w={{ base: "90%", md: "50%" }}
              textAlign={{ base: "left", md: "right" }}
            >
              <Text color="nairablue" fontWeight={700} fontSize="25px">
                Monthly Mega Millions Cashout
              </Text>
              <Text color="nairablue" fontSize={"25px"}>
                Get between 1 million to 5 million naira every month when you
                request for cashback for your ATM Withdrawals, POS Payments,
                Transfers or Mobile Money up to 10 times within a month.
              </Text>
            </Box>
          </Box>
        </Box>
      </Box>
      <FooterComponent />
    </div>
  );
}
